# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feb15_schools_comezo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_info',
            name='end_class',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='school_info',
            name='start_class',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
