# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feb15_schools_comezo', '0002_auto_20170219_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_class',
            name='section_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
