# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feb15_schools_comezo', '0003_exam_class_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='roll_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
