# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feb15_schools_comezo', '0004_auto_20170222_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=200)),
                ('section_id', models.CharField(max_length=200)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feb15_schools_comezo.school_info')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feb15_schools_comezo.teacher_info')),
            ],
        ),
    ]
